/**
 * @fileoverview The bundled clip modules. The only file in the app that names an asset path.
 *
 * Metro resolves `require` of an asset at build time and hands back a module id, so these
 * cannot be computed — `require(`../../../assets/sounds/${name}.wav`)` resolves to nothing
 * and fails as silence. Written out is the only form that works, which is why this file
 * exists separately from `./clips`: that table is pure and checkable, and this one is six
 * literals whose only possible mistake is a wrong name.
 *
 * `./clips.test.ts` reads this file as text and asserts it names exactly the basenames
 * `CLIPS` declares — the one check that catches a renamed asset before a device does.
 *
 * `notification.wav` is generated by `scripts/build-sounds.ts` and is deliberately **not**
 * required here: nothing references it, so Metro does not bundle it. It is waiting for
 * the local notification (N1/N2), which goes through the `expo-notifications` config
 * plugin rather than through this port.
 */

import type {BoundCue} from './clips';

/** Cue to Metro module id. */
export const SOURCES: Record<BoundCue, number> = {
  correct: require('../../../assets/sounds/correct_answer.wav'),
  wrong: require('../../../assets/sounds/wrong_answer.wav'),
  'stop-complete': require('../../../assets/sounds/celebration.wav'),
};
