/**
 * @fileoverview Lint config, including the architecture boundaries.
 *
 * The boundary rules are the point of this file. docs/05-architecture states that
 * pure logic never imports UI or storage, and a rule that is only written down
 * drifts — the design system already learned this and wired its own adherence
 * contract into CI before any code existed. These zones are the same idea for
 * layering.
 *
 * The dependency arrow points inward, toward the learning rules:
 *
 *   app/ · src/components/  ->  src/store/  ->  src/usecases/  ->  src/engine/
 *                                                    |               |
 *                                                    +--> src/ports/ +--> src/domain/
 *
 *   src/infra/ implements src/ports/ and is wired ONLY by src/composition/.
 *
 * To verify the zones actually bite, add `import {View} from 'react-native'` to a
 * file under src/engine/ and run `npm run lint`. It must fail.
 */

const expoConfig = require('eslint-config-expo/flat');
const prettierConfig = require('eslint-config-prettier');

/** Packages that mean "this file knows about a platform": UI, storage or bundler. */
const PLATFORM_PACKAGES = [
  'react',
  'react-*',
  'react-native',
  'react-native/*',
  'react-native-*',
  'expo',
  'expo-*',
  '@expo/*',
  '@expo-google-fonts/*',
  'uniwind',
  'uniwind/*',
  'zustand',
  'zustand/*',
];

/** Any import that reaches a layer, whether by alias or by relative path. */
const layer = name => [`@/${name}`, `@/${name}/**`, `**/${name}`, `**/${name}/**`];

const forbid = (message, ...groups) => ({
  'no-restricted-imports': ['error', {patterns: [{group: groups.flat(), message}]}],
});

module.exports = [
  ...expoConfig,
  prettierConfig,

  {
    ignores: [
      'dist/*',
      '.expo/*',
      'node_modules/*',
      // Generated by scripts/sync-design.ts and by Uniwind's Metro plugin.
      'src/theme/theme.generated.css',
      'src/theme/tokens.generated.ts',
      'src/theme/fonts.generated.ts',
      'src/theme/tokens/*',
      'src/uniwind-types.d.ts',
    ],
  },

  // ── zone 1 · domain ───────────────────────────────────────────────────────
  // The innermost layer. Progression and scheduling rules, and nothing else.
  {
    files: ['src/domain/**/*.ts'],
    rules: forbid(
      'src/domain is the innermost layer: it may import only from src/domain. ' +
        'Rules here must run with no platform, no storage and no clock of their own — ' +
        'pass the date in as a value.',
      layer('engine'),
      layer('usecases'),
      layer('ports'),
      layer('infra'),
      layer('store'),
      layer('components'),
      layer('theme'),
      PLATFORM_PACKAGES,
    ),
  },

  // ── zone 2 · engine ───────────────────────────────────────────────────────
  // The exercise machine. Receives values, returns values, touches no port.
  {
    files: ['src/engine/**/*.ts'],
    rules: forbid(
      'src/engine may import only src/engine and src/domain. It receives values and ' +
        'returns values — a use case does the loading and saving, which is what keeps ' +
        'the engine testable with no doubles at all.',
      layer('usecases'),
      layer('ports'),
      layer('infra'),
      layer('store'),
      layer('components'),
      layer('theme'),
      PLATFORM_PACKAGES,
    ),
  },

  // ── zone 3 · usecases ─────────────────────────────────────────────────────
  // Orchestration. The only layer that touches a port, and still no platform.
  {
    files: ['src/usecases/**/*.ts'],
    rules: forbid(
      'src/usecases orchestrates domain, engine and ports. It must not reach an ' +
        'adapter directly — depend on the port and let src/composition choose the ' +
        'implementation.',
      layer('infra'),
      layer('store'),
      layer('components'),
      layer('theme'),
      PLATFORM_PACKAGES,
    ),
  },

  // ── zone 4 · ports ────────────────────────────────────────────────────────
  // Interfaces over domain types. No implementation, no platform.
  {
    files: ['src/ports/**/*.ts'],
    rules: forbid(
      'src/ports declares interfaces over domain types. An import from infra would ' +
        'invert the dependency the port exists to create.',
      layer('engine'),
      layer('usecases'),
      layer('infra'),
      layer('store'),
      layer('components'),
      layer('theme'),
      PLATFORM_PACKAGES,
    ),
  },

  // ── zone 5 · UI ───────────────────────────────────────────────────────────
  // Screens and components read from the container, never from an adapter.
  {
    files: ['app/**/*.tsx', 'app/**/*.ts', 'src/components/**/*.tsx', 'src/store/**/*.ts'],
    rules: forbid(
      'Reach an adapter through src/composition/container, not directly. Naming a ' +
        'concrete adapter here is what makes swapping SQLite for an API a rewrite of ' +
        'the screens rather than a change of one line.',
      layer('infra'),
    ),
  },
];
