sonar.projectKey=trungtrung-community_app
sonar.organization=trungtrung-community
sonar.sources=src,app,scripts
sonar.tests=src,scripts,tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/*.generated.ts,**/*.generated.css,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*.generated.ts,app/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
